# 下面是每个组件对应的IP配置
domain_name: samples.network
nfs_server: 10.0.0.160

sysdb: 10.0.0.154
nats: 10.0.0.158
router: 10.0.0.158
cloud_controller: 10.0.0.158
uaa: 10.0.0.158
stager: 10.0.0.158
health_manager: 10.0.0.158
deas:
  - 10.0.0.158
mango: 10.0.0.158

filesystem_gateway: 10.0.0.158
mysql_gateway: 10.0.0.158
mysql_nodes: 
  - 10.0.0.158
postgresql_gateway: 10.0.0.158
postgresql_nodes:
  - 10.0.0.158
oracle_gateway: 10.0.0.158
oracle_nodes:
  - 10.0.0.158
memcached_gateway: 10.0.0.158
memcached_nodes:
  - 10.0.0.158
redis_gateway: 10.0.0.158
redis_nodes:
  - 10.0.0.158
mongodb_gateway: 10.0.0.158
mongodb_nodes:
  - 10.0.0.158
rabbitmq_gateway: 10.0.0.158
rabbitmq_nodes:
  - 10.0.0.158
cloud9_gateway: 10.0.0.158
cloud9_nodes:
  - 10.0.0.158
svn_gateway: 10.0.0.158
svn_nodes:
  - 10.0.0.158


